### ISSUE TITLE
[Feature] Add short names to config

### ISSUE THREAD

**Issue by nxexox** [nxexox/pymlup#10]
## Problem
Я пишу конфиг руками или указываю в баш команде какие-то параметры конфига. Тогда мне нужно прописывать полный путь импорта в некоторых параметрах "mlup.ml.binarization.onnx.InferenceSessionBinarizer". Это очень неудобно

## Solution
Для существующих в mlup классов, использовать alias, которые позволят в конфиге писать короткие слова.

## Examples

```yaml
version: '1'
ml:
  data_transformer_for_predict: pandas
  data_transformer_for_predictet: numpy
```

```bash
mlup run -m my_model --up.data_transformer_for_predict=pandas --up.data_transformer_for_predictet=numpy
```
